/**
 * Skill Optimizer (Offline Optimization Loop)
 *
 * Inspired by GEPA (Gradient-free Evolution of Prompt Agents, ICLR 2026 Oral).
 *
 * Flow:
 *   1. Read recent execution traces from ~/.cmbcoworkagent/traces/
 *   2. Identify "interesting" sessions: high tool-call count, repeated patterns,
 *      or sessions where the agent retried or corrected itself.
 *   3. For each identified session, call an LLM to:
 *        a. Summarize what the agent did
 *        b. Suggest a skill (or patch an existing skill) that would make
 *           future runs faster / more reliable
 *   4. Return a list of SkillOptimizationCandidate objects — NOT applied yet.
 *   5. The caller (IPC handler / UI) presents candidates to the user for review.
 *   6. User approves/rejects each candidate; approved ones are written via
 *      the existing manage_skill infrastructure.
 */

import { ChatOpenAI } from "@langchain/openai"
import { HumanMessage, SystemMessage } from "@langchain/core/messages"
import { join } from "path"
import { existsSync, readdirSync, readFileSync } from "fs"
import { homedir } from "os"
import { v4 as uuid } from "uuid"
import { getCustomSkillsDir } from "../../storage"
import { readRecentTraces, readThreadTraces } from "../trace/collector"
import type { AgentTrace, TraceStep } from "../trace/types"

// ─────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────

export type CandidateAction = "create" | "patch"

/**
 * A proposed skill improvement generated by the optimizer.
 * Must be reviewed and approved by the user before being applied.
 */
export interface SkillOptimizationCandidate {
  /** Unique ID for this candidate (used by the approval UI) */
  candidateId: string
  /** Whether to create a new skill or patch an existing one */
  action: CandidateAction
  /** Skill file name / directory (snake_case) */
  skillId: string
  /** Human-readable skill name */
  name: string
  /**
   * Trigger description — when should the agent load this skill?
   * This is the most important field; it controls skill injection.
   */
  description: string
  /** Full proposed SKILL.md content (including YAML frontmatter) */
  proposedContent: string
  /**
   * Reasoning: why did the optimizer suggest this?
   * Shown to the user in the review UI.
   */
  rationale: string
  /**
   * The trace IDs that motivated this candidate.
   * Shown in the review UI as "based on N sessions".
   */
  sourceTraceIds: string[]
  /** When this candidate was generated */
  generatedAt: string
  /** Approval status (set by UI) */
  status: "pending" | "approved" | "rejected"
}

/** Result of a single optimization run. */
export interface OptimizationRunResult {
  /** When the run started */
  startedAt: string
  /** When the run ended */
  endedAt: string
  /** How many traces were analyzed */
  tracesAnalyzed: number
  /** Generated candidates (may be empty if nothing interesting found) */
  candidates: SkillOptimizationCandidate[]
  /** Summary message from the optimizer */
  summary: string
}

// ─────────────────────────────────────────────────────────
// Prompts
// ─────────────────────────────────────────────────────────

const ANALYZER_SYSTEM_PROMPT = `You are an expert at analyzing AI agent execution traces and suggesting reusable skills.

Your job:
1. Read the execution traces provided (JSON format)
2. Identify patterns that indicate a reusable skill would help:
   - High tool-call count (agent had to "figure things out" step by step)
   - Multiple retries or corrections
   - Domain-specific knowledge the agent had to infer
   - Repeated tool sequences that form a pattern
3. For each pattern, propose ONE skill in the exact format below.

Output ONLY a JSON array of skill proposals. Each proposal must have:
{
  "skillId": "snake_case_identifier",
  "name": "Human Readable Name",
  "description": "When should this skill be loaded? Describe the user intent that should trigger it. Be specific.",
  "rationale": "Why does this skill help? What problem does it solve?",
  "content": "Full SKILL.md content including YAML frontmatter"
}

SKILL.md format:
\`\`\`
---
name: skill-name
description: Trigger description (same as 'description' field above)
---

# Overview
Brief description.

## When to use
List of situations.

## Steps / Guidelines
Concrete instructions for the agent.

## Examples
Optional examples of tool usage or patterns.
\`\`\`

Rules:
- Output ONLY valid JSON, no markdown, no explanation outside the JSON.
- If no skill is worth creating, output an empty array: []
- Maximum 3 proposals per analysis.
- Skills should be specific and actionable, not generic advice.
- The description field (trigger) is the MOST important — make it precise.`

// ─────────────────────────────────────────────────────────
// Trace summarization helpers
// ─────────────────────────────────────────────────────────

/** Score how "interesting" a trace is for optimization purposes. */
function interestScore(trace: AgentTrace): number {
  let score = 0
  // More tool calls = more complex = more worth capturing
  score += Math.min(trace.totalToolCalls * 2, 20)
  // Retries / corrections often mean the agent had to learn something
  const allText = trace.steps.map((s) => s.assistantText).join(" ").toLowerCase()
  if (allText.includes("retry") || allText.includes("重试")) score += 5
  if (allText.includes("actually") || allText.includes("wait") || allText.includes("actually,")) score += 3
  if (allText.includes("let me reconsider") || allText.includes("重新考虑")) score += 5
  // Errors indicate a learning opportunity
  if (trace.outcome === "error") score += 3
  return score
}

/** Create a compact trace summary for the LLM (avoids huge token usage). */
function summarizeTrace(trace: AgentTrace): string {
  const toolList = trace.steps
    .flatMap((s) => s.toolCalls.map((tc) => tc.name))
    .join(", ")

  const stepSummaries = trace.steps
    .map((s) => {
      const tools = s.toolCalls.map((tc) => `${tc.name}(${JSON.stringify(tc.args).slice(0, 80)})`).join("; ")
      const text = s.assistantText.slice(0, 200).replace(/\n/g, " ")
      return `  Step ${s.index}: [${tools || "no tools"}] ${text}`
    })
    .join("\n")

  return `Trace ${trace.traceId.slice(0, 8)} | ${trace.outcome} | ${trace.totalToolCalls} tool calls
User message: ${trace.userMessage.slice(0, 150)}
Tools used: ${toolList}
Steps:
${stepSummaries}`
}

// ─────────────────────────────────────────────────────────
// Existing skills reader
// ─────────────────────────────────────────────────────────

function readExistingCustomSkills(): string {
  const dir = getCustomSkillsDir()
  if (!existsSync(dir)) return "(no custom skills yet)"
  try {
    const skills = readdirSync(dir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => {
        const mdPath = join(dir, d.name, "SKILL.md")
        if (!existsSync(mdPath)) return null
        const content = readFileSync(mdPath, "utf-8").slice(0, 400)
        return `--- ${d.name} ---\n${content}`
      })
      .filter(Boolean)
    return skills.length ? skills.join("\n\n") : "(no custom skills yet)"
  } catch {
    return "(error reading skills)"
  }
}

// ─────────────────────────────────────────────────────────
// SkillOptimizer
// ─────────────────────────────────────────────────────────

export interface SkillOptimizerOptions {
  /** LLM model instance to use for analysis */
  model: ChatOpenAI
  /** How many recent traces to load for analysis (default: 30) */
  traceLimit?: number
  /** Minimum interest score to include a trace (default: 4) */
  minInterestScore?: number
  /** Thread ID to scope analysis to a single thread (optional) */
  threadId?: string
}

export class SkillOptimizer {
  private readonly model: ChatOpenAI
  private readonly traceLimit: number
  private readonly minInterestScore: number
  private readonly threadId?: string

  constructor(opts: SkillOptimizerOptions) {
    this.model = opts.model
    this.traceLimit = opts.traceLimit ?? 30
    this.minInterestScore = opts.minInterestScore ?? 4
    this.threadId = opts.threadId
  }

  /**
   * Run the optimization loop:
   *  1. Load traces
   *  2. Filter by interest score
   *  3. Call LLM to generate skill candidates
   *  4. Return candidates (NOT applied)
   */
  async run(): Promise<OptimizationRunResult> {
    const startedAt = new Date().toISOString()

    // Load traces
    const rawTraces = this.threadId
      ? readThreadTraces(this.threadId)
      : readRecentTraces(this.traceLimit)

    // Filter interesting traces
    const interesting = rawTraces
      .map((t) => ({ trace: t, score: interestScore(t) }))
      .filter(({ score }) => score >= this.minInterestScore)
      .sort((a, b) => b.score - a.score)
      .slice(0, 10) // cap at 10 traces to avoid huge prompts
      .map(({ trace }) => trace)

    if (interesting.length === 0) {
      return {
        startedAt,
        endedAt: new Date().toISOString(),
        tracesAnalyzed: rawTraces.length,
        candidates: [],
        summary: `分析了 ${rawTraces.length} 条 trace，未发现值得优化的模式（所有任务复杂度较低或无重复规律）。`
      }
    }

    // Build the prompt
    const existingSkills = readExistingCustomSkills()
    const traceSummaries = interesting.map(summarizeTrace).join("\n\n")

    const userPrompt = `# Existing Custom Skills
${existingSkills}

# Execution Traces to Analyze (${interesting.length} traces)
${traceSummaries}

Based on these traces, suggest skills that would make future runs faster and more reliable.
Only suggest skills that are NOT already covered by existing custom skills above.
Output JSON array only.`

    // Call LLM
    let rawResponse = ""
    try {
      const response = await this.model.invoke([
        new SystemMessage(ANALYZER_SYSTEM_PROMPT),
        new HumanMessage(userPrompt)
      ])
      rawResponse = typeof response.content === "string"
        ? response.content
        : JSON.stringify(response.content)
    } catch (e) {
      return {
        startedAt,
        endedAt: new Date().toISOString(),
        tracesAnalyzed: rawTraces.length,
        candidates: [],
        summary: `LLM 调用失败: ${String(e)}`
      }
    }

    // Parse response
    const candidates = this._parseCandidates(rawResponse, interesting)
    const endedAt = new Date().toISOString()

    return {
      startedAt,
      endedAt,
      tracesAnalyzed: rawTraces.length,
      candidates,
      summary: candidates.length > 0
        ? `分析了 ${rawTraces.length} 条 trace（选取 ${interesting.length} 条高价值），生成了 ${candidates.length} 个技能优化候选。`
        : `分析了 ${rawTraces.length} 条 trace，LLM 判断暂无值得创建的新技能。`
    }
  }

  private _parseCandidates(raw: string, sourceTraces: AgentTrace[]): SkillOptimizationCandidate[] {
    // Strip markdown code fences if LLM included them
    const cleaned = raw
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/```\s*$/i, "")
      .trim()

    let proposals: Array<{
      skillId: string
      name: string
      description: string
      rationale: string
      content: string
    }>

    try {
      proposals = JSON.parse(cleaned)
      if (!Array.isArray(proposals)) proposals = []
    } catch {
      console.warn("[SkillOptimizer] Failed to parse LLM response as JSON:", cleaned.slice(0, 200))
      return []
    }

    const sourceTraceIds = sourceTraces.map((t) => t.traceId)
    const now = new Date().toISOString()

    return proposals
      .filter((p) => p.skillId && p.name && p.description && p.content)
      .map((p) => ({
        candidateId: uuid(),
        action: "create" as CandidateAction,
        skillId: p.skillId,
        name: p.name,
        description: p.description,
        proposedContent: p.content,
        rationale: p.rationale ?? "",
        sourceTraceIds,
        generatedAt: now,
        status: "pending" as const
      }))
  }
}

// ─────────────────────────────────────────────────────────
// Candidate persistence (in-memory for session; written on approval)
// ─────────────────────────────────────────────────────────

/** In-memory store of current optimization run candidates. */
let _currentCandidates: SkillOptimizationCandidate[] = []

export function setCandidates(candidates: SkillOptimizationCandidate[]): void {
  _currentCandidates = candidates
}

export function getCandidates(): SkillOptimizationCandidate[] {
  return _currentCandidates
}

export function updateCandidateStatus(
  candidateId: string,
  status: "approved" | "rejected"
): SkillOptimizationCandidate | null {
  const candidate = _currentCandidates.find((c) => c.candidateId === candidateId)
  if (candidate) {
    candidate.status = status
  }
  return candidate ?? null
}

export function clearCandidates(): void {
  _currentCandidates = []
}
